"""16.0 database

Revision ID: 58ad65bf513f
Revises: None
Create Date: 2016-04-17 10:34:30.100012

"""

# revision identifiers, used by Alembic.
revision = '58ad65bf513f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
