"""initial migration

Revision ID: ab96ea947a91
Revises: None
Create Date: 2016-03-18 12:10:17.787952

"""

# revision identifiers, used by Alembic.
revision = 'ab96ea947a91'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    ### end Alembic commands ###
